package ncsu.csc.homework;

import ncsu.csc.datastructures.AdjacencyListGraph;
import ncsu.csc.datastructures.Graph;
import ncsu.csc.datastructures.Vertex;

public class Main {

	public static void main(String[] args) {
	
		Graph<City, Integer> usa = new AdjacencyListGraph<City, Integer>();
		
		Vertex<City> albanyGA = usa.insertVertex(new City("albanyGA", 31.58, 84.17));
		Vertex<City> albanyNY = usa.insertVertex(new City("albanyNY", 42.66, 73.78));
		Vertex<City> albuquerque = usa.insertVertex(new City("albuquerque", 35.11, 106.61));
		Vertex<City> atlanta = usa.insertVertex(new City("atlanta", 33.76, 84.40));
		Vertex<City> augusta = usa.insertVertex(new City("augusta", 33.43, 82.02));
		Vertex<City> austin = usa.insertVertex(new City("austin", 30.30, 97.75));
		Vertex<City> bakersfield = usa.insertVertex(new City("bakersfield", 35.36, 119.03));
		Vertex<City> baltimore = usa.insertVertex(new City("baltimore", 39.31, 76.62));
		Vertex<City> batonRouge = usa.insertVertex(new City("batonRouge", 30.46, 91.14));
		Vertex<City> beaumont = usa.insertVertex(new City("beaumont", 30.08, 94.13));
		Vertex<City> boise = usa.insertVertex(new City("boise", 43.61, 116.24));
		Vertex<City> boston = usa.insertVertex(new City("boston", 42.32, 71.09));
		Vertex<City> buffalo = usa.insertVertex(new City("buffalo", 42.90, 78.85));
		Vertex<City> calgary = usa.insertVertex(new City("calgary", 51.00, 114.00));
		Vertex<City> charlotte = usa.insertVertex(new City("charlotte", 35.21, 80.83));
		Vertex<City> chattanooga = usa.insertVertex(new City("chattanooga", 35.05, 85.27));
		Vertex<City> chicago = usa.insertVertex(new City("chicago", 41.84, 87.68));
		Vertex<City> cincinnati = usa.insertVertex(new City("cincinnati", 39.14, 84.50));
		Vertex<City> cleveland = usa.insertVertex(new City("cleveland", 41.48, 81.67));
		Vertex<City> coloradoSprings = usa.insertVertex(new City("coloradoSprings", 38.86, 104.79));
		Vertex<City> columbus = usa.insertVertex(new City("columbus", 39.99, 82.99));
		Vertex<City> dallas = usa.insertVertex(new City("dallas", 32.80, 96.79));
		Vertex<City> dayton = usa.insertVertex(new City("dayton", 39.76, 84.20));
		Vertex<City> daytonaBeach = usa.insertVertex(new City("daytonaBeach", 29.21, 81.04));
		Vertex<City> denver = usa.insertVertex(new City("denver", 39.73, 104.97));
		Vertex<City> desMoines = usa.insertVertex(new City("desMoines", 41.59, 93.62));
		Vertex<City> elPaso = usa.insertVertex(new City("elPaso", 31.79, 106.42));
		Vertex<City> eugene = usa.insertVertex(new City("eugene", 44.06, 123.11));
		Vertex<City> europe = usa.insertVertex(new City("europe", 48.87, -2.33));
		Vertex<City> ftWorth = usa.insertVertex(new City("ftWorth", 32.74, 97.33));
		Vertex<City> fresno = usa.insertVertex(new City("fresno", 36.78, 119.79));
		Vertex<City> grandJunction = usa.insertVertex(new City("grandJunction", 39.08, 108.56));
		Vertex<City> greenBay = usa.insertVertex(new City("greenBay", 44.51, 88.02));
		Vertex<City> greensboro = usa.insertVertex(new City("greensboro", 36.08, 79.82));
		Vertex<City> houston = usa.insertVertex(new City("houston", 29.76, 95.38));
		Vertex<City> indianapolis = usa.insertVertex(new City("indianapolis", 39.79, 86.15));
		Vertex<City> jacksonville = usa.insertVertex(new City("jacksonville", 30.32, 81.66));
		Vertex<City> japan = usa.insertVertex(new City("japan", 35.68, 220.23));
		Vertex<City> kansasCity = usa.insertVertex(new City("kansasCity", 39.08, 94.56));
		Vertex<City> keyWest = usa.insertVertex(new City("keyWest", 24.56, 81.78));
		Vertex<City> lafayette = usa.insertVertex(new City("lafayette", 30.21, 92.03));
		Vertex<City> lakeCity = usa.insertVertex(new City("lakeCity", 30.19, 82.64));
		Vertex<City> laredo = usa.insertVertex(new City("laredo", 27.52, 99.49));
		Vertex<City> lasVegas = usa.insertVertex(new City("lasVegas", 36.19, 115.22));
		Vertex<City> lincoln = usa.insertVertex(new City("lincoln", 40.81, 96.68));
		Vertex<City> littleRock = usa.insertVertex(new City("littleRock", 34.74, 92.33));
		Vertex<City> losAngeles = usa.insertVertex(new City("losAngeles", 34.03, 118.17));
		Vertex<City> macon = usa.insertVertex(new City("macon", 32.83, 83.65));
		Vertex<City> medford = usa.insertVertex(new City("medford", 42.33, 122.86));
		Vertex<City> memphis = usa.insertVertex(new City("memphis", 35.12, 89.97));
		Vertex<City> mexia = usa.insertVertex(new City("mexia", 31.68, 96.48));
		Vertex<City> mexico = usa.insertVertex(new City("mexico", 19.40, 99.12));
		Vertex<City> miami = usa.insertVertex(new City("miami", 25.79, 80.22));
		Vertex<City> midland = usa.insertVertex(new City("midland", 43.62, 84.23));
		Vertex<City> milwaukee = usa.insertVertex(new City("milwaukee", 43.05, 87.96));
		Vertex<City> minneapolis = usa.insertVertex(new City("minneapolis", 44.96, 93.27));
		Vertex<City> modesto = usa.insertVertex(new City("modesto", 37.66, 120.99));
		Vertex<City> montreal = usa.insertVertex(new City("montreal", 45.50, 73.67));
		Vertex<City> nashville = usa.insertVertex(new City("nashville", 36.15, 86.76));
		Vertex<City> newHaven = usa.insertVertex(new City("newHaven", 41.31, 72.92));
		Vertex<City> newOrleans = usa.insertVertex(new City("newOrleans", 29.97, 90.06));
		Vertex<City> newYork = usa.insertVertex(new City("newYork", 40.70, 73.92));
		Vertex<City> norfolk = usa.insertVertex(new City("norfolk", 36.89, 76.26));
		Vertex<City> oakland = usa.insertVertex(new City("oakland", 37.80, 122.23));
		Vertex<City> oklahomaCity = usa.insertVertex(new City("oklahomaCity", 35.48, 97.53));
		Vertex<City> omaha = usa.insertVertex(new City("omaha", 41.26, 96.01));
		Vertex<City> orlando = usa.insertVertex(new City("orlando", 28.53, 81.38));
		Vertex<City> ottawa = usa.insertVertex(new City("ottawa", 45.42, 75.69));
		Vertex<City> pensacola = usa.insertVertex(new City("pensacola", 30.44, 87.21));
		Vertex<City> philadelphia = usa.insertVertex(new City("philadelphia", 40.72, 76.12));
		Vertex<City> phoenix = usa.insertVertex(new City("phoenix", 33.53, 112.08));
		Vertex<City> pittsburgh = usa.insertVertex(new City("pittsburgh", 40.40, 79.84));
		Vertex<City> pointReyes = usa.insertVertex(new City("pointReyes", 38.07, 122.81));
		Vertex<City> portland = usa.insertVertex(new City("portland", 45.52, 122.64));
		Vertex<City> providence = usa.insertVertex(new City("providence", 41.80, 71.36));
		Vertex<City> provo = usa.insertVertex(new City("provo", 40.24, 111.66));
		Vertex<City> raleigh = usa.insertVertex(new City("raleigh", 35.82, 78.64));
		Vertex<City> redding = usa.insertVertex(new City("redding", 40.58, 122.37));
		Vertex<City> reno = usa.insertVertex(new City("reno", 39.53, 119.82));
		Vertex<City> richmond = usa.insertVertex(new City("richmond", 37.54, 77.46));
		Vertex<City> rochester = usa.insertVertex(new City("rochester", 43.17, 77.61));
		Vertex<City> sacramento = usa.insertVertex(new City("sacramento", 38.56, 121.47));
		Vertex<City> salem = usa.insertVertex(new City("salem", 44.93, 123.03));
		Vertex<City> salinas = usa.insertVertex(new City("salinas", 36.68, 121.64));
		Vertex<City> saltLakeCity = usa.insertVertex(new City("saltLakeCity", 40.75, 111.89));
		Vertex<City> sanAntonio = usa.insertVertex(new City("sanAntonio", 29.45, 98.51));
		Vertex<City> sanDiego = usa.insertVertex(new City("sanDiego", 32.78, 117.15));
		Vertex<City> sanFrancisco = usa.insertVertex(new City("sanFrancisco", 37.76, 122.44));
		Vertex<City> sanJose = usa.insertVertex(new City("sanJose", 37.30, 121.87));
		Vertex<City> sanLuisObispo = usa.insertVertex(new City("sanLuisObispo", 35.27, 120.66));
		Vertex<City> santaFe = usa.insertVertex(new City("santaFe", 35.67, 105.96));
		Vertex<City> saultSteMarie = usa.insertVertex(new City("saultSteMarie", 46.49, 84.35));
		Vertex<City> savannah = usa.insertVertex(new City("savannah", 32.05, 81.10));
		Vertex<City> seattle = usa.insertVertex(new City("seattle", 47.63, 122.33));
		Vertex<City> stLouis = usa.insertVertex(new City("stLouis", 38.63, 90.24));
		Vertex<City> stamford = usa.insertVertex(new City("stamford", 41.07, 73.54));
		Vertex<City> stockton = usa.insertVertex(new City("stockton", 37.98, 121.30));
		Vertex<City> tallahassee = usa.insertVertex(new City("tallahassee", 30.45, 84.27));
		Vertex<City> tampa = usa.insertVertex(new City("tampa", 27.97, 82.46));
		Vertex<City> thunderBay = usa.insertVertex(new City("thunderBay", 48.38, 89.25));
		Vertex<City> toledo = usa.insertVertex(new City("toledo", 41.67, 83.58));
		Vertex<City> toronto = usa.insertVertex(new City("toronto", 43.65, 79.38));
		Vertex<City> tucson = usa.insertVertex(new City("tucson", 32.21, 110.92));
		Vertex<City> tulsa = usa.insertVertex(new City("tulsa", 36.13, 95.94));
		Vertex<City> uk1 = usa.insertVertex(new City("uk1", 51.30, 0.00));
		Vertex<City> uk2 = usa.insertVertex(new City("uk2", 51.30, 0.00));
		Vertex<City> vancouver = usa.insertVertex(new City("vancouver", 49.25, 123.10));
		Vertex<City> washington = usa.insertVertex(new City("washington", 38.91, 77.01));
		Vertex<City> westPalmBeach = usa.insertVertex(new City("westPalmBeach", 26.43, 80.03));
		Vertex<City> wichita = usa.insertVertex(new City("wichita", 37.69, 97.34));
		Vertex<City> winnipeg = usa.insertVertex(new City("winnipeg", 49.90, 97.13));
		Vertex<City> yuma = usa.insertVertex(new City("yuma", 32.69, 114.62));
		
		usa.insertEdge(albanyNY, montreal, 226);
		usa.insertEdge(albanyNY, boston, 166);
		usa.insertEdge(albanyNY, rochester, 148);
		usa.insertEdge(albanyGA, tallahassee, 120);
		usa.insertEdge(albanyGA, macon, 106);
		usa.insertEdge(albuquerque, elPaso, 267);
		usa.insertEdge(albuquerque, santaFe, 61);
		usa.insertEdge(atlanta, macon, 82);
		usa.insertEdge(atlanta, chattanooga, 117);
		usa.insertEdge(augusta, charlotte, 161);
		usa.insertEdge(augusta, savannah, 131);
		usa.insertEdge(austin, houston, 186);
		usa.insertEdge(austin, sanAntonio, 79);
		usa.insertEdge(bakersfield, losAngeles, 112);
		usa.insertEdge(bakersfield, fresno, 107);
		usa.insertEdge(baltimore, philadelphia, 102);
		usa.insertEdge(baltimore, washington, 45);
		usa.insertEdge(batonRouge, lafayette, 50);
		usa.insertEdge(batonRouge, newOrleans, 80);
		usa.insertEdge(beaumont, houston, 69);
		usa.insertEdge(beaumont, lafayette, 122);
		usa.insertEdge(boise, saltLakeCity, 349);
		usa.insertEdge(boise, portland, 428);
		usa.insertEdge(boston, providence, 51);
		usa.insertEdge(buffalo, toronto, 105);
		usa.insertEdge(buffalo, rochester, 64);
		usa.insertEdge(buffalo, cleveland, 191);
		usa.insertEdge(buffalo, toronto, 105);
		usa.insertEdge(buffalo, rochester, 164);
		usa.insertEdge(buffalo, cleveland, 191);
		usa.insertEdge(calgary, vancouver, 605);
		usa.insertEdge(calgary, winnipeg, 829);
		usa.insertEdge(charlotte, greensboro, 91);
		usa.insertEdge(chattanooga, nashville, 129);
		usa.insertEdge(chicago, milwaukee, 90);
		usa.insertEdge(chicago, midland, 279);
		usa.insertEdge(cincinnati, indianapolis, 110);
		usa.insertEdge(cincinnati, dayton, 56);
		usa.insertEdge(cleveland, pittsburgh, 157);
		usa.insertEdge(cleveland, columbus, 142);
		usa.insertEdge(coloradoSprings, denver, 70);
		usa.insertEdge(coloradoSprings, santaFe, 316);
		usa.insertEdge(columbus, dayton, 72);
		usa.insertEdge(dallas, denver, 792);
		usa.insertEdge(dallas, mexia, 83);
		usa.insertEdge(daytonaBeach, jacksonville, 92);
		usa.insertEdge(daytonaBeach, orlando, 54);
		usa.insertEdge(denver, wichita, 523);
		usa.insertEdge(denver, grandJunction, 246);
		usa.insertEdge(desMoines, omaha, 135);
		usa.insertEdge(desMoines, minneapolis, 246);
		usa.insertEdge(elPaso, sanAntonio, 580);
		usa.insertEdge(elPaso, tucson, 320);
		usa.insertEdge(eugene, salem, 63);
		usa.insertEdge(eugene, medford, 165);
		usa.insertEdge(europe, philadelphia, 3939);
		usa.insertEdge(ftWorth, oklahomaCity, 209);
		usa.insertEdge(fresno, modesto, 109);
		usa.insertEdge(grandJunction, provo, 220);
		usa.insertEdge(greenBay, minneapolis, 304);
		usa.insertEdge(greenBay, milwaukee, 117);
		usa.insertEdge(greensboro, raleigh, 74);
		usa.insertEdge(houston, mexia, 165);
		usa.insertEdge(indianapolis, stLouis, 246);
		usa.insertEdge(jacksonville, savannah, 140);
		usa.insertEdge(jacksonville, lakeCity, 113);
		usa.insertEdge(japan, pointReyes, 5131);
		usa.insertEdge(japan, sanLuisObispo, 5451);
		usa.insertEdge(kansasCity, tulsa, 249);
		usa.insertEdge(kansasCity, stLouis, 256);
		usa.insertEdge(kansasCity, wichita, 190);
		usa.insertEdge(keyWest, tampa, 446);
		usa.insertEdge(lakeCity, tampa, 169);
		usa.insertEdge(lakeCity, tallahassee, 104);
		usa.insertEdge(laredo, sanAntonio, 154);
		usa.insertEdge(laredo, mexico, 741);
		usa.insertEdge(lasVegas, losAngeles, 275);
		usa.insertEdge(lasVegas, saltLakeCity, 486);
		usa.insertEdge(lincoln, wichita, 277);
		usa.insertEdge(lincoln, omaha, 58);
		usa.insertEdge(littleRock, memphis, 137);
		usa.insertEdge(littleRock, tulsa, 276);
		usa.insertEdge(losAngeles, sanDiego, 124);
		usa.insertEdge(losAngeles, sanLuisObispo, 182);
		usa.insertEdge(medford, redding, 150);
		usa.insertEdge(memphis, nashville, 210);
		usa.insertEdge(miami, westPalmBeach, 67);
		usa.insertEdge(midland, toledo, 82);
		usa.insertEdge(minneapolis, winnipeg, 463);
		usa.insertEdge(modesto, stockton, 29);
		usa.insertEdge(montreal, ottawa, 132);
		usa.insertEdge(newHaven, providence, 110);
		usa.insertEdge(newHaven, stamford, 92);
		usa.insertEdge(newOrleans, pensacola, 268);
		usa.insertEdge(newYork, philadelphia, 101);
		usa.insertEdge(norfolk, richmond, 92);
		usa.insertEdge(norfolk, raleigh, 174);
		usa.insertEdge(oakland, sanFrancisco, 8);
		usa.insertEdge(oakland, sanJose, 42);
		usa.insertEdge(oklahomaCity, tulsa, 105);
		usa.insertEdge(orlando, westPalmBeach, 168);
		usa.insertEdge(orlando, tampa, 84);
		usa.insertEdge(ottawa, toronto, 269);
		usa.insertEdge(pensacola, tallahassee, 120);
		usa.insertEdge(philadelphia, pittsburgh, 319);
		usa.insertEdge(philadelphia, newYork, 101);
		usa.insertEdge(philadelphia, uk1, 3548);
		usa.insertEdge(philadelphia, uk2, 3548);
		usa.insertEdge(phoenix, tucson, 117);
		usa.insertEdge(phoenix, yuma, 178);
		usa.insertEdge(pointReyes, redding, 215);
		usa.insertEdge(pointReyes, sacramento, 115);
		usa.insertEdge(portland, seattle, 174);
		usa.insertEdge(portland, salem, 47);
		usa.insertEdge(reno, saltLakeCity, 520);
		usa.insertEdge(reno, sacramento, 133);
		usa.insertEdge(richmond, washington, 105);
		usa.insertEdge(sacramento, sanFrancisco, 95);
		usa.insertEdge(sacramento, stockton, 51);
		usa.insertEdge(salinas, sanJose, 31);
		usa.insertEdge(salinas, sanLuisObispo, 137);
		usa.insertEdge(sanDiego, yuma, 172);
		usa.insertEdge(saultSteMarie, thunderBay, 442);
		usa.insertEdge(saultSteMarie, toronto, 436);
		usa.insertEdge(seattle, vancouver, 115);
		usa.insertEdge(thunderBay, winnipeg, 440);
		 	
		SearchHeuristicAStarUSA pathFinder = new SearchHeuristicAStarUSA();
		
		pathFinder.execute(usa, europe, japan);
		
	}
	
}
